//PROGRAM INI TIDAK SEMPURNA NAMUN BUKAN BERARTI CACAT HANYA TERDAPAT KETERBATASAN DALAM MENGINPUT DAN MENDELETE DATA YANG HANYA BISA DILAKUKAN DI DEPAN DAN DI BELAKANG
//JADI TIDAK MELAKUKAN INPUT ATAU DELETE DI TENGAH
//PRINT YANG DI JALANKAN JUGA TIDAK MENGGUNAKAN HAL SPESIFIK JADI PROGRAM INI AKAN PRINT SEMUA DATA JADI TIDAK BISA PRINT SPESIFIK DATA

public class Node<Pegawai> {
    Pegawai data;
    Node<Pegawai> next;
    public Node(Pegawai data) {
        this.data = data;
        this.next = null;
    }
    public Pegawai getData() {
        return data;
    }
}
